version: "3.9"

services:
  java_app:
    container_name: java_app
    image: nequi-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=r2dbc:postgresql://nequidemo.c38020aiw0br.us-east-2.rds.amazonaws.com:5432/nequi_demo?sslMode=require
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres