CREATE TABLE IF NOT EXISTS franquicia (id SERIAL PRIMARY KEY, nombre VARCHAR(255));
CREATE TABLE IF NOT EXISTS sucursal (id SERIAL PRIMARY KEY, nombre VARCHAR(255), id_franquicia INTEGER);
CREATE TABLE IF NOT EXISTS producto (id SERIAL PRIMARY KEY, nombre VARCHAR(255), cantidad INTEGER, id_sucursal INTEGER);
